# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9ab59967ac3de5aed873d2ab584c2b169be82b4c30b8e332a6fdc7e8ef98ae930dbced230cfc24f27ff105518a1b22aa0112773554d202497349a59a503a4e

test:
  secret_key_base: c6162cb16a73af9647b694187a11bea887d68b26458d60f54fe98608f299fb6906e5a7d90d823604d1cbeef3e5783e3f06b97a996db063b81411bbcdf96ccbb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
